FROM debian:latest

RUN apt update && apt upgrade -y

ENV DEBIAN_FRONTEND=noninteractive

# Install the necessary packages
RUN apt install -y \
    systemd systemd-sysv nano \
    git python3 python3-pip python3-setuptools \
    python3-numpy gcc make nodejs npm wget unzip \
    tar sudo dbus-x11 dbus net-tools gnu-which \
    libwebsockets-dev build-essential cmake git \
    libjson-c-dev xfce4 xfce4-terminal xfce4-goodies xterm \
    tigervnc-standalone-server tigervnc-xorg-extension rsyslog \
    bpfcc-tools libbpfcc libbpfcc-dev python3-bpfcc python3-geoip2 \
    && apt clean

# setup xstartup for xfce4
RUN mkdir -p /usr/local/vnc
COPY ./configs/xstartup /usr/local/vnc/xstartup
RUN chmod 0755 /usr/local/vnc/xstartup

# copy service files
COPY ./services/*.service /etc/systemd/system/
RUN chmod 0644 /etc/systemd/system/*.service

# copy rsyslog config files
COPY ./configs/rsyslog.conf /etc/rsyslog.conf
COPY ./configs/rsyslog.d/*.conf /etc/rsyslog.d/

# install novnc
RUN wget https://github.com/novnc/noVNC/archive/refs/tags/v1.5.0.tar.gz -O /tmp/novnc.tar.gz && \
    tar -xvf /tmp/novnc.tar.gz -C /usr/local/bin && \
    mv /usr/local/bin/noVNC-1.5.0 /usr/local/bin/novnc && \
    rm -f /tmp/novnc.tar.gz

# install websockify
RUN wget https://github.com/novnc/websockify/archive/refs/tags/v0.12.0.tar.gz -O /tmp/websockify.tar.gz && \
    tar -xvf /tmp/websockify.tar.gz -C /usr/local/bin && \
    mv /usr/local/bin/websockify-0.12.0 /usr/local/bin/websockify-install && \
    rm -f /tmp/websockify.tar.gz && \
    cd /usr/local/bin/websockify-install && \
    python3 setup.py install

# install ttyd
RUN wget https://github.com/tsl0922/ttyd/releases/download/1.7.7/ttyd.x86_64 -O /usr/local/bin/ttyd && \
    chmod +x /usr/local/bin/ttyd

# install maxmind geoip2
RUN wget https://github.com/P3TERX/GeoLite.mmdb/releases/download/2025.04.28/GeoLite2-City.mmdb -O /usr/local/share/GeoLite2-City.mmdb

# install ebpf scripts
RUN echo "none /sys/kernel/debug debugfs auto,rw,seclabel,relatime 0 0" >> /etc/fstab
COPY ./ebpf/usercommands.py /srv/usercommands.py
COPY ./ebpf/ip_geolocation.py /srv/ip_geolocation.py

# adds ebpf log rotate
COPY ./configs/logrotate.d/abra /etc/logrotate.d/abra

# create normal user
RUN useradd -m -s /bin/bash user && \
    echo "user:user" | chpasswd && \
    usermod -aG sudo user && \
    echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# set password for root
RUN echo "root:abratools" | chpasswd

#create /var/log/ebpf directory
RUN mkdir -p /var/log/ebpf && \
    chown root:root /var/log/ebpf && \
    chmod 755 /var/log/ebpf

# touch usercommands.log file
RUN touch /var/log/ebpf/usercommands.log && \
    chown root:root /var/log/ebpf/usercommands.log && \
    chmod 775 /var/log/ebpf/usercommands.log

# Not enabling eBPF services by default
# Enable and start the services
RUN systemctl enable dbus && \
    systemctl enable tigervnc@root.service && \
    systemctl enable novnc-websockify@root.service && \
    systemctl enable ttyd@root.service && \
    systemctl enable rsyslog && \
    systemctl enable ebpf_usercommands.service && \
    systemctl enable ebpf_ipgeolocation.service

# port 8888 = novnc, port 7681 = ttyd websocket
EXPOSE 5801 7681

# Start systemd
CMD ["/sbin/init"]